name:    suffix-trees-haskell
version: "1.0.0"

dependencies:
    - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
    - pretty-tree == 0.1.0.0
    - protolude
    - text
    - containers
    - parsec
    - QuickCheck
    - random
    - deepseq
    - regex-compat

default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  suffix-trees-haskell:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - suffix-trees-haskell
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - suffix-trees-haskell
    - hspec >=2.0.0

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
